nonsoolmate-official/nonsoolmate-client

nonsoolmateClient/package.json, nonsoolmateClient/src/components/onbordingheader/Header.tsx, nonsoolmateClient/src/components/onbordingheader/HeaderLeft.tsx, nonsoolmateClient/src/components/onbordingheader/HeaderRight.tsx, nonsoolmateClient/src/error/index.tsx, nonsoolmateClient/src/home/components/HomeHeader.tsx, nonsoolmateClient/src/home/components/HomeMemberInfoToggle.tsx, nonsoolmateClient/src/membership/components/BackgroundGrey.tsx, nonsoolmateClient/src/membership/components/Contents.tsx, nonsoolmateClient/src/membership/components/Title.tsx, nonsoolmateClient/src/membership/components/advantage/Advantage.tsx, nonsoolmateClient/src/membership/components/advantage/Summary.tsx, nonsoolmateClient/src/onboarding/components/advertise/Advertise.tsx, nonsoolmateClient/src/onboarding/components/advertise/Advertisement/Advertisement.tsx, nonsoolmateClient/src/onboarding/components/advertise/Advertisement/Reasons.tsx, nonsoolmateClient/src/onboarding/components/banner/Banner.tsx, nonsoolmateClient/src/onboarding/components/banner/HomeImg.tsx, nonsoolmateClient/src/onboarding/components/faq/FaQ.tsx, nonsoolmateClient/src/onboarding/components/faq/qna/Answer.tsx, nonsoolmateClient/src/onboarding/components/faq/qna/QnA.tsx, nonsoolmateClient/src/onboarding/components/footer/Buttons.tsx, nonsoolmateClient/src/onboarding/components/footer/Footer.tsx, nonsoolmateClient/src/onboarding/components/footer/FooterLeft.tsx, nonsoolmateClient/src/onboarding/components/footer/FooterRight.tsx, nonsoolmateClient/src/onboarding/components/footer/Sns.tsx, nonsoolmateClient/src/onboarding/components/univeristy/Univeristy.tsx, nonsoolmateClient/src/onboarding/index.tsx, nonsoolmateClient/src/signup/components/login/Login.tsx, nonsoolmateClient/src/signup/index.tsx, nonsoolmateClient/yarn.lock
- close #13 
**기타페이지들** 아이패드UI를 진행했습니다 !! 
반응형 코드 작성중에 **useMediaQuery**를 쓴것이 있어서 `yarn add react-responsive`로 새로운 패키지 설치했습니다 !! 
useMediaQuery는 아이패드일때 어떤 컴포넌트를 보이게 또는 안보이게 하기 위해서 설치했습니당
=> Feat/#13/on boarding/responsive UI

nonsoolmateClient/src/style/responsiveStyle.ts, nonsoolmateClient/src/takeTest/components/coachMark/TimerMark.tsx
=> [ TakeTest ] 반응형 수정

nonsoolmateClient/src/home/components/HomeHeader.tsx, nonsoolmateClient/src/home/index.tsx, nonsoolmateClient/src/membership/components/BackgroundGrey.tsx, nonsoolmateClient/src/membership/components/Contents.tsx, nonsoolmateClient/src/membership/components/Title.tsx, nonsoolmateClient/src/membership/components/advantage/Advantage.tsx, nonsoolmateClient/src/membership/components/advantage/Summary.tsx, nonsoolmateClient/src/onboarding/components/advertise/Advertise.tsx, nonsoolmateClient/src/onboarding/components/advertise/Advertisement/Advertisement.tsx, nonsoolmateClient/src/onboarding/components/footer/Footer.tsx, nonsoolmateClient/src/signup/components/login/Login.tsx, nonsoolmateClient/src/signup/index.tsx
=> [Home] 아이패드 반응형 구현

nonsoolmateClient/src/components/onbordingheader/buttons/LoginButton.tsx
=> [Onboarding] 헤더 로그인버튼

nonsoolmateClient/index.html, nonsoolmateClient/src/home/components/SelectedUniversityToggle.tsx, nonsoolmateClient/src/home/homeTest/HomeTestSet.tsx, nonsoolmateClient/src/style/globalStyle.ts
- close #23 
```
html,
body {
-ms-overflow-style: none; /* 인터넷 익스플로러  스크롤바 숨김 */
scrollbar-width: none; /* 파이어폭스 스크롤바 숨김 */
}
#root::-webkit-scrollbar {
display: none; /* 크롬, 사파리, 오페라, 엣지 스크롤바 숨김 */
}
```
`scrollbar-width: none;`
=> [Home] 아이패드 반응형 스크롤 제거

nonsoolmateClient/src/answer/components/PdfViewer.tsx, nonsoolmateClient/src/answer/components/PdfViewerWrapper.tsx, nonsoolmateClient/src/answer/components/TitleWrapper.tsx, nonsoolmateClient/src/answer/explanation/components/ImageSlider.tsx
- close #24
https://github.com/nonsoolmate-official/nonsoolmate-client/assets/102568726/4ae7cf3e-fc82-4103-bfcd-3ac58e832d3a
=> [ Answer ] 문제/해제 아이패드 반응형 구현

nonsoolmateClient/src/home/components/HomeIpadSide.tsx, nonsoolmateClient/src/home/components/HomeSide.tsx, nonsoolmateClient/src/home/components/SelectedUniversityToggle.tsx, nonsoolmateClient/src/home/homePractice/HomePractice.tsx, nonsoolmateClient/src/home/homeStudy/HomeStudy.tsx, nonsoolmateClient/src/home/homeTest/HomeTestSet.tsx, nonsoolmateClient/src/home/homeTest/HomeTestUnset.tsx, nonsoolmateClient/src/style/layout/SetUnsetLayout.ts
=> [Home] 아이패드뷰 수정

nonsoolmateClient/src/home/components/HomeHeader.tsx, nonsoolmateClient/src/home/components/HomeSide.tsx, nonsoolmateClient/src/home/homeTest/HomeTestSet.tsx, nonsoolmateClient/src/home/index.tsx
=> [ Home ] 높이 calc없애고 아이패드뷰

nonsoolmateClient/src/home/components/HomeMemberInfoToggle.tsx, nonsoolmateClient/src/mypage/components/MemberInfo.tsx, nonsoolmateClient/src/mypage/components/MypageSide.tsx, nonsoolmateClient/src/mypage/index.tsx, nonsoolmateClient/src/router.tsx
=> [ Mypage ] 마이페이지 UI 구현

nonsoolmateClient/src/home/api/serverInitController.ts, nonsoolmateClient/src/home/homeTest/HomeTestSet.tsx, nonsoolmateClient/src/takeTest/components/testPaper/TestPaper.tsx
=> [ Home ] 아산 유스프러너 데모데이용 시험 기록 초기화 버튼 추가

nonsoolmateClient/src/home/api/serverInitController.ts, nonsoolmateClient/src/home/homeTest/HomeTestSet.tsx
=> [ Home ] 임시 초기화 버튼 삭제

nonsoolmateClient/package.json, nonsoolmateClient/src/membership/components/subscribe/PurchaseButton.tsx, nonsoolmateClient/src/payment/components/Fail.tsx, nonsoolmateClient/src/payment/components/Success.tsx, nonsoolmateClient/src/payment/index.tsx, nonsoolmateClient/src/router.tsx, nonsoolmateClient/yarn.lock
=> [ Payment ] 토스페이먼츠 결제 연동

nonsoolmateClient/src/main.tsx, nonsoolmateClient/src/payment/components/Success.tsx, nonsoolmateClient/src/payment/index.tsx
- close #53 
개발 환경에서 test 할 때는 결제 요청 두 번 가지 않도록 react strict mode 풀고 해주세요!!
=> [ Payment ] post 요청 논술메이트로 보내도록 변경

nonsoolmateClient/src/answer/api/getCorrectionPageData.ts, nonsoolmateClient/src/answer/components/ExplainHeader.tsx, nonsoolmateClient/src/answer/components/PdfViewerWrapper.tsx, nonsoolmateClient/src/answer/components/TitleWrapper.tsx, nonsoolmateClient/src/answer/correction/index.tsx, nonsoolmateClient/src/answer/explanation/index.tsx, nonsoolmateClient/src/assets/icon/backToListIc.svg, nonsoolmateClient/src/assets/index.ts
=> [ Answer ] 디자인 변경 사항 반영

nonsoolmateClient/src/home/api/getSelectUniversities.ts, nonsoolmateClient/src/home/api/getSelectUniversityExams.ts, nonsoolmateClient/src/home/api/patchSelectUniversities.ts, nonsoolmateClient/src/home/components/SelectedUniversityToggle.tsx, nonsoolmateClient/src/home/components/UniversityModal.tsx, nonsoolmateClient/src/home/homeTest/HomeTest.tsx, nonsoolmateClient/src/home/homeTest/HomeTestSet.tsx, nonsoolmateClient/src/home/hooks/useGetSelectUniversityExams.ts
=> [ Home ] response 필드 examId로 고치기

nonsoolmateClient/src/pages/membership/components/subscribe/PurchaseButton.tsx, nonsoolmateClient/src/pages/payment/components/orderInfo/OrderInfo.tsx, nonsoolmateClient/src/pages/payment/index.tsx
=> [ Fix ] 카드 등록 / 변경 후 payment 페이지 돌아올 때 이슈 해결

src/pages/home/components/HomeHeader.tsx, src/pages/socialLogin/hooks/usePostLogin.ts
- close #149 
서버에서 더미데이터 추가 완료해 시험보기 페이지로 이동 가능하다고 전달받아 수정했습니다!
=> [ Feat ] QA 위한 dev 페이지 이동 수정

src/pages/mypage/api/getMentor.ts, src/pages/mypage/components/Mentor.tsx
- close #148 
버튼 하나 추가했고요, 버튼 클릭했을 때 _blank 옵션을 사용해서 새 창에서 열리도록 해주었습니다!
https://github.com/user-attachments/assets/4890eb3a-6c1f-482d-bfc2-c8458fda9b45
=> [ Feat ] 프리미엄 1대1 질의응답 버튼 추가

src/pages/payment/components/paymentInfo/Agreements.tsx
- close #170 
약관 동의 텍스트에 노션 링크 연결해두었습니다~ 디자인 쪽에서 전달 받은 시안이 없어 임의로 호버 시 색상 지정했는데 요청 후 변경 예정입니다!
=> [ QA ] 약관 동의 텍스트에 노션 링크 연결

src/pages/mypage/components/MembershipInfo.tsx
=> [Hotfix] 멤버십 해지 & 연장 버튼 이슈 해결

src/pages/socialLogin/hooks/usePostLogin.ts
- close #199 
간단한 변경 사항 반영입니다~
=> [ Feat ] 로그인 변경 사항 반영
